// Auto-generated by scripts/generate-env.js
window.EMAILJS_PUBLIC_KEY = "-k4-0oqXmABkG8AFP";
window.EMAILJS_SERVICE_ID = "service_73qnm3i";
window.EMAILJS_TEMPLATE_ID = "template_hnfzwqc";
window.EMAILJS_TO_EMAIL = "saurabhsingh26rajput@gmail.com";
