const fs = require('fs');
const path = require('path');
require('dotenv').config();

const envContent = `// Auto-generated by scripts/generate-env.js
window.EMAILJS_PUBLIC_KEY = "${process.env.EMAILJS_PUBLIC_KEY || ''}";
window.EMAILJS_SERVICE_ID = "${process.env.EMAILJS_SERVICE_ID || ''}";
window.EMAILJS_TEMPLATE_ID = "${process.env.EMAILJS_TEMPLATE_ID || ''}";
window.EMAILJS_TO_EMAIL = "${process.env.EMAILJS_TO_EMAIL || ''}";
`;

fs.writeFileSync(path.join(__dirname, '../env.js'), envContent);
console.log('env.js generated successfully.');
